CREATE (a:Start {id: 1}),
       (b:Node {id: 2}),
       (c:Node {id: 3}),
       (d:Node {id: 4}),
       (e:Node {id: 5}),
       (f:Node {id: 6}),
       (a)-[:CONNECTS {cost: 1.0}]->(b),
       (a)-[:CONNECTS {cost: 5.0}]->(c),
       (b)-[:CONNECTS {cost: 1.0}]->(d),
       (c)-[:CONNECTS {cost: 5.0}]->(e),
       (d)-[:CONNECTS {cost: 1.0}]->(e),
       (e)-[:CONNECTS {cost: 1.0}]->(f)
