CREATE (a:Node {name: 'A'}),
       (b:Node {name: 'B'}),
       (c:Node {name: 'C'}),
       (d:Node {name: 'D'}),
       (e:Node {name: 'E'}),
       (f:Node {name: 'F'}),
       (g:Node {name: 'G'}),
       (h:Node {name: 'H'}),
       (i:Node {name: 'I'}),
       (j:Node {name: 'J'}),
       (k:Node {name: 'K'}),
       (l:Node {name: 'L'})

CREATE (a)-[:CONNECTED]->(b),
       (a)-[:CONNECTED]->(c),
       (b)-[:CONNECTED]->(d),
       (b)-[:CONNECTED]->(e),
       (c)-[:CONNECTED]->(f),
       (c)-[:CONNECTED]->(g),
       (d)-[:CONNECTED]->(h),
       (d)-[:CONNECTED]->(i),
       (e)-[:CONNECTED]->(j),
       (e)-[:CONNECTED]->(k),
       (f)-[:CONNECTED]->(l);
