#!/bin/bash -e
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd "$DIR"
source "$DIR/environment/util.sh"

function setup_virtualenv () {
    pushd $1 > /dev/null
    echo "Setting up virtualenv for: $1"

    # remove old virtualenv
    if [ -d ve3 ]; then
        rm -rf ve3
    fi

    # create new virtualenv
    python3 -m venv ve3 || exit 1
    source ve3/bin/activate
    pip --timeout 1000 install -r requirements.txt || exit 1
    deactivate

    popd > /dev/null
}

prep_testing=true
while(($#)); do
    case "$1" in
      --skip-prep-testing)
          shift
          prep_testing=false
      ;;
      *)
          # unknown option
          echo "Invalid argument provided: $1"
          print_help
          exit 1
      ;;
    esac
done

DISTRO=$(operating_system)
ARCHITECTURE=$(architecture)

# this should fix --break-system-packages not being available in older distros
export PIP_BREAK_SYSTEM_PACKAGES=1

# Fix for centos 7 during release
if [[ "$ci" == "false" ]]; then
  if [ "${DISTRO}" = "centos-7" ] || [ "${DISTRO}" = "debian-11" ] || [ "${DISTRO}" = "amzn-2" ]; then
    if python3 -m pip show virtualenv >/dev/null 2>/dev/null; then
      python3 -m pip uninstall -y virtualenv
    fi
    python3 -m pip install virtualenv
  fi
else
  if [ "${DISTRO}" = "centos-7" ] || [ "${DISTRO}" = "amzn-2" ]; then
    if python3 -m pip show virtualenv >/dev/null 2>/dev/null; then
      python3 -m pip uninstall -y virtualenv
    fi
    python3 -m pip install --user virtualenv
  fi
fi

if [[ "$prep_testing" == "true" ]]; then
  setup_virtualenv tests/gql_behave
  setup_virtualenv tests/stress
  setup_virtualenv tests/integration/ldap
  setup_virtualenv tests/query_modules
  cd tests
  ./setup.sh
  cd ..
fi
