os:
  Linux:
    distro: [null, ANY]
compiler:
  gcc:
    asan: [null, True, False]
    ubsan: [null, True, False]
    tsan: [null, True, False]
  clang:
    asan: [null, True, False]
    ubsan: [null, True, False]
    tsan: [null, True, False]
