CREATE (a:Node {id: 0});
CREATE (a:Node {id: 1});
CREATE (a:Node {id: 2});
CREATE (a:Node {id: 3});
CREATE (a:Node {id: 4});
CREATE (a:Node {id: 5});
CREATE (a:Node {id: 6});
CREATE (a:Node {id: 7});
CREATE (a:Node {id: 8});
CREATE (a:Node {id: 9});
CREATE (a:Node {id: 10});
CREATE (a:Node {id: 11});
CREATE (a:Node {id: 12});
CREATE (a:Node {id: 13});
MATCH (a:Node {id: 0}) MATCH (b:Node {id: 11}) CREATE (a)-[:RELATION]->(b);
MATCH (a:Node {id: 1}) MATCH (b:Node {id: 3}) CREATE (a)-[:RELATION]->(b);
MATCH (a:Node {id: 3}) MATCH (b:Node {id: 2}) CREATE (a)-[:RELATION]->(b);
MATCH (a:Node {id: 3}) MATCH (b:Node {id: 8}) CREATE (a)-[:RELATION]->(b);
MATCH (a:Node {id: 4}) MATCH (b:Node {id: 3}) CREATE (a)-[:RELATION]->(b);
MATCH (a:Node {id: 6}) MATCH (b:Node {id: 3}) CREATE (a)-[:RELATION]->(b);
MATCH (a:Node {id: 7}) MATCH (b:Node {id: 9}) CREATE (a)-[:RELATION]->(b);
MATCH (a:Node {id: 8}) MATCH (b:Node {id: 1}) CREATE (a)-[:RELATION]->(b);
MATCH (a:Node {id: 8}) MATCH (b:Node {id: 3}) CREATE (a)-[:RELATION]->(b);
MATCH (a:Node {id: 9}) MATCH (b:Node {id: 6}) CREATE (a)-[:RELATION]->(b);
MATCH (a:Node {id: 9}) MATCH (b:Node {id: 0}) CREATE (a)-[:RELATION]->(b);
MATCH (a:Node {id: 10}) MATCH (b:Node {id: 1}) CREATE (a)-[:RELATION]->(b);
MATCH (a:Node {id: 10}) MATCH (b:Node {id: 11}) CREATE (a)-[:RELATION]->(b);
MATCH (a:Node {id: 11}) MATCH (b:Node {id: 1}) CREATE (a)-[:RELATION]->(b);
MATCH (a:Node {id: 11}) MATCH (b:Node {id: 10}) CREATE (a)-[:RELATION]->(b);
MATCH (a:Node {id: 11}) MATCH (b:Node {id: 8}) CREATE (a)-[:RELATION]->(b);
