#!/usr/bin/env python3

import multiprocessing as mp
import os
import subprocess

WORK_DIRECTORY = os.getcwd()
CPP_DIRECTORY = f"{WORK_DIRECTORY}/cpp"
PY_DIRECTORY = f"{WORK_DIRECTORY}/python"

#################################################
#            Unit Test C++ modules              #
#################################################
CPP_BUILD_DIRECTORY = f"{CPP_DIRECTORY}/build"
if not os.path.exists(CPP_BUILD_DIRECTORY):
    print("No C++ build directory in ./cpp/build !")
    exit(1)

# Run ctest
os.chdir(CPP_BUILD_DIRECTORY)
core_count = mp.cpu_count()
subprocess.run(["ctest", f"-j{core_count}"])

#################################################
#           Unit Test Python modules            #
#################################################

os.environ["PYTHONPATH"] = PY_DIRECTORY
os.chdir(PY_DIRECTORY)
subprocess.run(["pytest", "."])
