CREATE INDEX ON :__mg_vertex__(__mg_id__);
CREATE (:__mg_vertex__ {__mg_id__: 0, `country`: "Austria", `value`: 6});
CREATE (:__mg_vertex__ {__mg_id__: 1, `country`: "Hungary", `value`: 7});
CREATE (:__mg_vertex__ {__mg_id__: 2, `country`: "Romania", `value`: 8});
CREATE (:__mg_vertex__ {__mg_id__: 3, `country`: "Bulgaria", `value`: 9});
CREATE (:__mg_vertex__ {__mg_id__: 4, `country`: "Spain", `value`: 10});
CREATE (:__mg_vertex__ {__mg_id__: 5, `country`: "Latvia", `value`: 11});
CREATE (:__mg_vertex__ {__mg_id__: 6, `country`: "Russia", `value`: 12});
CREATE (:__mg_vertex__ {__mg_id__: 7, `country`: "Poland", `value`: 13});
CREATE (:__mg_vertex__ {__mg_id__: 8, `country`: "Czech Republic", `value`: 14});
CREATE (:__mg_vertex__ {__mg_id__: 9, `country`: "Moldova", `value`: 15});
MATCH (u:__mg_vertex__), (v:__mg_vertex__) WHERE u.__mg_id__ = 0 AND v.__mg_id__ = 1 CREATE (u)-[:`NEIGHBOUR` {`value`: "test"}]->(v);
MATCH (u:__mg_vertex__), (v:__mg_vertex__) WHERE u.__mg_id__ = 2 AND v.__mg_id__ = 1 CREATE (u)-[:`NEIGHBOUR` {`value`: "hello"}]->(v);
MATCH (u:__mg_vertex__), (v:__mg_vertex__) WHERE u.__mg_id__ = 4 AND v.__mg_id__ = 6 CREATE (u)-[:`NOT_NEIGHBOUR` {`value`: "world"}]->(v);
MATCH (u:__mg_vertex__), (v:__mg_vertex__) WHERE u.__mg_id__ = 5 AND v.__mg_id__ = 0 CREATE (u)-[:`NOT_NEIGHBOUR` {`value`: "to properties"}]->(v);
DROP INDEX ON :__mg_vertex__(__mg_id__);
MATCH (u) REMOVE u:__mg_vertex__, u.__mg_id__;