#!/bin/bash
set -euo pipefail
# Regenerates the committed uv lockfiles for MAGE's python dependencies.
#
# Every requirements.txt gets a fully pinned requirements.lock next to it, which
# install_python_requirements.sh --uv installs instead of the loose pins (and
# mgbuild.sh ships into the build container for the MAGE unit tests). Run this
# after changing any of the requirements files and commit the result.
#
# Requirements are resolved for the interpreter memgraph embeds (3.12) and for
# every architecture the file is used on. A lock is only written when all of
# them resolve identically, so a single committed file stays valid everywhere;
# if that ever stops holding, this script fails instead of picking a winner.

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR/../../.."

PYTHON_VERSION=3.12
AMD64_PLATFORM=x86_64-manylinux_2_34
ARM64_PLATFORM=aarch64-manylinux_2_34

if ! command -v uv >/dev/null 2>&1; then
  echo "uv is not on PATH; install it first (e.g. pip install --user uv)" >&2
  exit 1
fi

WORK_DIR="$(mktemp -d)"
trap 'rm -rf "$WORK_DIR"' EXIT

compile () {
  local requirements="$1"
  shift
  local lock="${requirements%.txt}.lock"
  local platform
  local reference=""

  for platform in "$@"; do
    uv pip compile \
      --quiet --no-header \
      --python-version "$PYTHON_VERSION" \
      --python-platform "$platform" \
      --index-strategy unsafe-best-match \
      --emit-index-url \
      "$requirements" -o "$WORK_DIR/$platform.lock"

    if [[ -z "$reference" ]]; then
      reference="$platform"
    elif ! diff -q "$WORK_DIR/$reference.lock" "$WORK_DIR/$platform.lock" >/dev/null; then
      echo "ERROR: $requirements resolves differently for $reference and $platform:" >&2
      diff "$WORK_DIR/$reference.lock" "$WORK_DIR/$platform.lock" >&2 || true
      echo "Teach install_python_requirements.sh about per-architecture locks before committing." >&2
      exit 1
    fi
  done

  {
    echo "# Autogenerated by release/package/mage/compile_requirements_locks.sh - do not edit."
    echo "# Resolved from ${requirements} for python ${PYTHON_VERSION} on: $*"
    cat "$WORK_DIR/$reference.lock"
  } > "$lock"
  echo "wrote $lock"
}

compile src/mage/python/requirements.txt            "$AMD64_PLATFORM" "$ARM64_PLATFORM"
compile src/mage/python/requirements-gpu.txt        "$AMD64_PLATFORM"
compile src/mage/python/tests/requirements.txt      "$AMD64_PLATFORM" "$ARM64_PLATFORM"
compile src/auth/reference_modules/requirements.txt "$AMD64_PLATFORM" "$ARM64_PLATFORM"
