CREATE INDEX ON :__mg_vertex__(__mg_id__);
CREATE (:__mg_vertex__ {__mg_id__: 0, `country`: "Croatia", `value`: 1});
CREATE (:__mg_vertex__ {__mg_id__: 1, `country`: "Germany", `value`: 2});
CREATE (:__mg_vertex__ {__mg_id__: 10, `country`: "Latvia", `value`: 11, `country_id`: 6});
CREATE (:__mg_vertex__ {__mg_id__: 11, `country`: "Russia", `value`: 12, `country_id`: 7});
CREATE (:__mg_vertex__ {__mg_id__: 12, `country`: "Poland", `value`: 13, `country_id`: 8});
CREATE (:__mg_vertex__ {__mg_id__: 13, `country`: "Czech Republic", `value`: 14, `country_id`: 9});
CREATE (:__mg_vertex__ {__mg_id__: 14, `country`: "Moldova", `value`: 15, `country_id`: 10});
CREATE (:__mg_vertex__ {__mg_id__: 2, `country`: "United Kingdom", `value`: 3});
CREATE (:__mg_vertex__ {__mg_id__: 3, `country`: "France", `value`: 4});
CREATE (:__mg_vertex__ {__mg_id__: 4, `country`: "Italy", `value`: 5});
CREATE (:__mg_vertex__ {__mg_id__: 5, `country`: "Austria", `value`: 6});
CREATE (:__mg_vertex__ {__mg_id__: 6, `country`: "Hungary", `value`: 7});
CREATE (:__mg_vertex__ {__mg_id__: 7, `country`: "Romania", `value`: 8});
CREATE (:__mg_vertex__ {__mg_id__: 8, `country`: "Bulgaria", `value`: 9, `country_id`: 4});
CREATE (:__mg_vertex__ {__mg_id__: 9, `country`: "Spain", `value`: 10, `country_id`: 5});
MATCH (u:__mg_vertex__), (v:__mg_vertex__) WHERE u.__mg_id__ = 5 AND v.__mg_id__ = 6 CREATE (u)-[:`NEIGHBOUR`]->(v);
MATCH (u:__mg_vertex__), (v:__mg_vertex__) WHERE u.__mg_id__ = 7 AND v.__mg_id__ = 6 CREATE (u)-[:`NEIGHBOUR`]->(v);
MATCH (u:__mg_vertex__), (v:__mg_vertex__) WHERE u.__mg_id__ = 9 AND v.__mg_id__ = 11 CREATE (u)-[:`NOT_NEIGHBOUR`]->(v);
MATCH (u:__mg_vertex__), (v:__mg_vertex__) WHERE u.__mg_id__ = 10 AND v.__mg_id__ = 5 CREATE (u)-[:`NOT_NEIGHBOUR`]->(v);
DROP INDEX ON :__mg_vertex__(__mg_id__);
MATCH (u) REMOVE u:__mg_vertex__, u.__mg_id__;
