CREATE INDEX ON :__mg_vertex__(__mg_id__);
CREATE (:__mg_vertex__ {__mg_id__: 0, `value`: 1, `country`: "Croatia"});
CREATE (:__mg_vertex__ {__mg_id__: 1, `value`: 2, `country`: "Germany"});
CREATE (:__mg_vertex__ {__mg_id__: 2, `value`: 3, `country`: "United Kingdom"});
CREATE (:__mg_vertex__ {__mg_id__: 3, `value`: 4, `country`: "France"});
CREATE (:__mg_vertex__ {__mg_id__: 4, `value`: 5, `country`: "Italy"});
CREATE (:__mg_vertex__ {__mg_id__: 5, `value`: 6, `country`: "Austria"});
CREATE (:__mg_vertex__ {__mg_id__: 6, `value`: 7, `country`: "Hungary"});
CREATE (:__mg_vertex__ {__mg_id__: 7, `value`: 8, `country`: "Romania"});
CREATE (:__mg_vertex__ {__mg_id__: 8, `country_id`: 4, `value`: 9, `country`: "Bulgaria"});
CREATE (:__mg_vertex__ {__mg_id__: 9, `country_id`: 5, `value`: 10, `country`: "Spain"});
CREATE (:__mg_vertex__ {__mg_id__: 10, `country_id`: 6, `value`: 11, `country`: "Latvia"});
CREATE (:__mg_vertex__ {__mg_id__: 11, `country_id`: 7, `value`: 12, `country`: "Russia"});
CREATE (:__mg_vertex__ {__mg_id__: 12, `country_id`: 8, `value`: 13, `country`: "Poland"});
CREATE (:__mg_vertex__ {__mg_id__: 13, `country_id`: 9, `value`: 14, `country`: "Czech Republic"});
CREATE (:__mg_vertex__ {__mg_id__: 14, `country_id`: 10, `value`: 15, `country`: "Moldova"});
MATCH (u:__mg_vertex__), (v:__mg_vertex__) WHERE u.__mg_id__ = 5 AND v.__mg_id__ = 6 CREATE (u)-[:`NEIGHBOUR`]->(v);
MATCH (u:__mg_vertex__), (v:__mg_vertex__) WHERE u.__mg_id__ = 7 AND v.__mg_id__ = 6 CREATE (u)-[:`NEIGHBOUR`]->(v);
MATCH (u:__mg_vertex__), (v:__mg_vertex__) WHERE u.__mg_id__ = 9 AND v.__mg_id__ = 11 CREATE (u)-[:`NOT_NEIGHBOUR`]->(v);
MATCH (u:__mg_vertex__), (v:__mg_vertex__) WHERE u.__mg_id__ = 10 AND v.__mg_id__ = 5 CREATE (u)-[:`NOT_NEIGHBOUR`]->(v);
DROP INDEX ON :__mg_vertex__(__mg_id__);
MATCH (u) REMOVE u:__mg_vertex__, u.__mg_id__;