// Copyright 2026 Memgraph Ltd.
//
// Use of this software is governed by the Business Source License
// included in the file licenses/BSL.txt; by using this file, you agree to be bound by the terms of the Business Source
// License, and you may not use this file except in compliance with the Business Source License.
//
// As of the Change Date specified in that file, in accordance with
// the Business Source License, use of this software will be governed
// by the Apache License, Version 2.0, included in the file
// licenses/APL.txt.

#pragma once

#include <atomic>
#include <coroutine>
#include <memory>
#include <type_traits>

#include "query/frontend/semantic/symbol_table.hpp"
#include "query/metadata.hpp"
#include "query/parameters.hpp"
#include "query/plan/profile.hpp"
#include "storage/v2/commit_args.hpp"
#include "utils/async_timer.hpp"
#include "utils/counter.hpp"
#include "utils/priority_thread_pool.hpp"

#include "query/frame_change.hpp"
#include "query/hops_limit.hpp"

namespace memgraph::memory {
class ArenaPool;
}  // namespace memgraph::memory

namespace memgraph::metrics {
struct DatabaseMetricHandles;
}  // namespace memgraph::metrics

namespace memgraph::query {

class FineGrainedAuthChecker;
class TriggerContextCollector;

enum class TransactionStatus {
  IDLE,
  ACTIVE,
  VERIFYING,
  TERMINATED,
  STARTED_COMMITTING,
  STARTED_ROLLBACK,
};

struct Scope {
  bool in_merge{false};
};

struct EvaluationContext {
  /// Memory for allocations during evaluation of a *single* Pull call.
  ///
  /// Although the assigned memory may live longer than the duration of a Pull
  /// (e.g. memory is the same as the whole execution memory), you have to treat
  /// it as if the lifetime is only valid during the Pull.
  utils::MemoryResource *memory{utils::NewDeleteResource()};
  int64_t timestamp{-1};
  Parameters parameters{};
  /// All properties indexable via PropertyIx
  std::vector<storage::PropertyId> properties{};
  /// All labels indexable via LabelIx
  std::vector<storage::LabelId> labels{};
  /// All edgetypes indexable via EdgeTypeIx
  std::vector<storage::EdgeTypeId> edgetypes{};
  /// All counters generated by `counter` function, mutable because the function
  /// modifies the values
  mutable std::unordered_map<std::string, int64_t> counters{};
  Scope scope{};
};

std::vector<storage::PropertyId> NamesToProperties(const std::vector<std::string> &property_names, DbAccessor *dba);

std::vector<storage::LabelId> NamesToLabels(const std::vector<std::string> &label_names, DbAccessor *dba);

std::vector<storage::EdgeTypeId> NamesToEdgeTypes(const std::vector<std::string> &edgetype_names, DbAccessor *dba);

/// Result of a throttled stop-check: continue executing, abort (with reason), or yield the worker.
/// Used by StoppingContext::CheckAbortOrYield at the same call sites as AbortCheck so the execution
/// layer can honour both transaction abort AND scheduler-driven cooperative yield in one check.
struct StopOrYieldResult {
  enum class Action { Continue, Abort, Yield };
  Action action{Action::Continue};
  AbortReason abort_reason{AbortReason::NO_ABORT};  // meaningful only when action == Abort
};

struct StoppingContext {
  // Even though this is called `StoppingContext`. TransactionStatus is used for more
  std::atomic<TransactionStatus> *transaction_status{nullptr};
  std::atomic<bool> *is_shutting_down{nullptr};
  std::shared_ptr<utils::AsyncTimer> timer{};
  std::shared_ptr<std::atomic<uint8_t>> exception_occurred{nullptr};  // Used only for parallel execution

  /// Per-worker cooperative-yield flag (points into WorkerYieldRegistry's signal block; nullptr when not
  /// running on a scheduler worker). The scheduler sets it to ask the running task to yield its worker at
  /// the next check point; the task suspends there and the pool reschedules it. nullptr => never yields,
  /// i.e. legacy behaviour. Wired by the runner in a later PR; null here so this is a pure no-op now.
  std::atomic<bool> *yield_requested{nullptr};

  auto MustAbort() const noexcept -> AbortReason {
    if (transaction_status && transaction_status->load(std::memory_order_acquire) == TransactionStatus::TERMINATED)
        [[unlikely]] {
      return AbortReason::TERMINATED;
    }
    if (is_shutting_down && is_shutting_down->load(std::memory_order_acquire)) [[unlikely]] {
      return AbortReason::SHUTDOWN;
    }
    if (timer && timer->IsExpired()) [[unlikely]] {
      return AbortReason::TIMEOUT;
    }
    if (exception_occurred && exception_occurred->load(std::memory_order_acquire)) [[unlikely]] {
      return AbortReason::EXCEPTION;
    }
    return AbortReason::NO_ABORT;
  }

  /// True if the scheduler has asked the running task to yield its worker. Cheap atomic load; only
  /// consulted when the throttling counter allows (see CheckAbortOrYield). nullptr => never yields.
  auto ShouldYield() const noexcept -> bool {
    return yield_requested && yield_requested->load(std::memory_order_acquire);
  }

  /// Combined throttled check for the execution layer. When maybe_check() fires, returns Abort (with
  /// reason) if the query must stop, else Yield if the scheduler requested it, else Continue. Abort
  /// strictly precedes Yield (a terminated/timed-out query must not be politely rescheduled). Off the
  /// throttle it returns Continue without touching the abort/yield state. Not thread-safe wrt maybe_check.
  auto CheckAbortOrYield(utils::ResettableCounter &maybe_check) const noexcept -> StopOrYieldResult {
    if (!maybe_check()) {
      return {StopOrYieldResult::Action::Continue, AbortReason::NO_ABORT};
    }
    if (auto const reason = MustAbort(); reason != AbortReason::NO_ABORT) [[unlikely]] {
      return {StopOrYieldResult::Action::Abort, reason};
    }
    if (ShouldYield()) [[unlikely]] {
      return {StopOrYieldResult::Action::Yield, AbortReason::NO_ABORT};
    }
    return {StopOrYieldResult::Action::Continue, AbortReason::NO_ABORT};
  }

  auto MakeMaybeAborter(std::size_t n = 20) const noexcept {
    return [maybe_check_abort = utils::ResettableCounter{n}, ctx = *this]() -> AbortReason {
      // Not thread safe
      return maybe_check_abort() ? ctx.MustAbort() : AbortReason::NO_ABORT;
    };
  }
};

struct ExecutionContext {
  DbAccessor *db_accessor{nullptr};
  SymbolTable symbol_table;
  EvaluationContext evaluation_context;
  StoppingContext stopping_context;
  bool is_profile_query{false};
  std::chrono::duration<double> profile_execution_time{0};
  plan::ProfilingStats stats;
  plan::ProfilingStats *stats_root{nullptr};
  ExecutionStats execution_stats;
  TriggerContextCollector *trigger_context_collector{nullptr};
  FrameChangeCollector *frame_change_collector{nullptr};
  std::shared_ptr<QueryUserOrRole> user_or_role;
  std::shared_ptr<QueryUserOrRole> triggering_user{nullptr};
  int64_t number_of_hops{0};
  HopsLimit hops_limit;
  std::optional<uint64_t> periodic_commit_frequency;
  std::shared_ptr<FineGrainedAuthChecker> auth_checker{nullptr};
  std::shared_ptr<storage::DatabaseProtector> protector;
  bool is_main{true};
  std::optional<size_t> parallel_execution{std::nullopt};  // if set, number of threads to use for parallel execution
  utils::PriorityThreadPool *worker_pool{nullptr};
  // Arena pool for the database owning this query. Parallel query workers
  // acquire from it when work leaves the main query thread, so TLS-scoped
  // allocations still attribute to the parent DB.
  memgraph::memory::ArenaPool *db_arena_pool{nullptr};
  metrics::DatabaseMetricHandles *metric_handles{nullptr};

  /// Cooperative-yield channel (the IRREDUCIBLE leaf->driver link). When a coroutine yields at a
  /// YieldPointAwaitable deep in the pull chain, await_suspend stores the suspended LEAF handle here so
  /// the seam driver can resume that exact frame on the next step. Points at a slot OWNED by the active
  /// pull driver (set/cleared by the driver's RAII scope, not by callers) — nullptr when no driver is
  /// active or yield is suppressed (e.g. a synchronous nested sub-pull). nullptr here (no driver wires
  /// it yet), so this is a pure no-op until the scheduler/driver PR lands.
  std::coroutine_handle<> *suspended_task_handle_ptr{nullptr};

  /// True while an Enabled PullDriverScope is active on THIS context. Guards against two Enabled drivers
  /// fighting over suspended_task_handle_ptr on the same context. Per-context (NOT thread_local) so a
  /// parked query that yielded with its driver alive does not false-trip the guard when another query
  /// runs on the same worker. Suppressed scopes do not touch it.
  bool enabled_driver_active{false};

  /// EVENT-PARK flag (c3.0). Set to true by ProgressAwaitable::await_suspend when it successfully
  /// registers a progress waiter and suspends (i.e. RegisterProgressWaiter returned true). Read and
  /// cleared by ResumePullStep immediately after target.resume() returns, BEFORE the existing Yielded
  /// slot check. Maps to PullRunResult::EventParked in the driver, which propagates up as
  /// PullOutcome::EventParked — distinct from the yield-kind PullOutcome::Parked.
  ///
  /// INVARIANT: only written by ProgressAwaitable::await_suspend (deep in the coro); only read/cleared
  /// by ResumePullStep (the sole driver). No cross-thread race: both sides run on the same worker while
  /// the coroutine is suspended.
  ///
  /// Reset to false by PullDriverScope(Enabled) at scope construction so each drive starts clean.
  bool event_parked{false};

  auto commit_args() -> storage::CommitArgs;
};

static_assert(std::is_move_assignable_v<ExecutionContext>, "ExecutionContext must be move assignable!");
static_assert(std::is_move_constructible_v<ExecutionContext>, "ExecutionContext must be move constructible!");

inline plan::ProfilingStatsWithTotalTime GetStatsWithTotalTime(const ExecutionContext &context) {
  return plan::ProfilingStatsWithTotalTime{context.stats, context.profile_execution_time};
}

}  // namespace memgraph::query
