/** @file include.hpp
 *  @brief Links all restful resources to the application
 *
 *  This file is autogenerated by the python script link_resources.py
 *  
 *  YOU SHOULD NOT EDIT THIS FILE MANUALLY!
 */

#ifndef MEMGRAPH_API_RESOURCES_INCLUDE_HPP
#define MEMGRAPH_API_RESOURCES_INCLUDE_HPP

#include <list>
#include <memory>

#include "api/restful/resource.hpp"
#include "speedy/speedy.hpp"

#include "node.hpp"

static std::list<std::unique_ptr<RestfulResource>> resources;

template <class T>
void insert(sp::Speedy& app)
{
    resources.push_back(std::unique_ptr<RestfulResource>(new T(app)));
}

void init(sp::Speedy& app)
{
    insert<Node>(app);
}

#endif
