/** @file include.hpp
 *  @brief Links all restful resources to the application
 *
 *  This file is autogenerated by the python script link_resources.py
 *  
 *  YOU SHOULD NOT EDIT THIS FILE MANUALLY!
 *
 *  well, only if you're editing the template file, that's ok :)
 */

#ifndef MEMGRAPH_API_RESOURCES_INCLUDE_HPP
#define MEMGRAPH_API_RESOURCES_INCLUDE_HPP

#include <list>
#include <memory>

#include "utils/ioc/container.hpp"
#include "api/restful/resource.hpp"

#include "transactions/engine.hpp"
#include "threading/task.hpp"
#include "speedy/speedy.hpp"

#include "node.hpp"
#include "node.hpp"

template <class T>
void insert(ioc::Container& container, const std::string& path)
{
    auto app = container.resolve<sp::Speedy>();
    auto resource = container.singleton<T, Task, Db>();
    resource->link(*app, path);
}

void init(ioc::Container& container)
{
    insert<Nodes>(container, "/node");
    insert<Node>(container, "/node/{id:\\d+}");
}

#endif
