version: "3"

services:
  mgbuild_v4_debian-11-arm:
    build:
      context: debian-11-arm
      args:
        TOOLCHAIN_VERSION: "v4"
    container_name: "mgbuild_v4_debian-11-arm"

  mgbuild_v4_ubuntu_v4_22.04-arm:
    build:
      context: ubuntu-22.04-arm
      args:
        TOOLCHAIN_VERSION: "v4"
    container_name: "mgbuild_v4_ubuntu-22.04-arm"
