version: "3"
services:
  # NOTE: build > context > args are injected via mgbuild.sh script.

  mgbuild_v6_debian-11-arm:
    image: "memgraph/mgbuild:v6_debian-11-arm"
    build:
      context: debian-11-arm
      args:
        TOOLCHAIN_VERSION: "v6"
    extra_hosts:
      - "mgdeps-cache:host-gateway"
      - "bench-graph-api:100.124.112.121"
    container_name: "mgbuild_v6_debian-11-arm"

  mgbuild_v6_debian-12-arm:
    image: "memgraph/mgbuild:v6_debian-12-arm"
    build:
      context: debian-12-arm
      args:
        TOOLCHAIN_VERSION: "v6"
    extra_hosts:
      - "mgdeps-cache:host-gateway"
      - "bench-graph-api:100.124.112.121"
    container_name: "mgbuild_v6_debian-12-arm"

  mgbuild_v6_ubuntu-24.04-arm:
    image: "memgraph/mgbuild:v6_ubuntu-24.04-arm"
    build:
      context: ubuntu-24.04-arm
      args:
        TOOLCHAIN_VERSION: "v6"
    extra_hosts:
      - "mgdeps-cache:host-gateway"
      - "bench-graph-api:100.124.112.121"
    container_name: "mgbuild_v6_ubuntu-24.04-arm"
