version: "3"

services:
  mgbuild_v4_debian-11-arm:
    image: "memgraph/mgbuild:v4_debian-11-arm"
    build:
      context: debian-11-arm
      args:
        TOOLCHAIN_VERSION: "v4"
    extra_hosts:
      - "mgdeps-cache:10.42.16.10"
      - "bench-graph-api:10.42.16.10"
    container_name: "mgbuild_v4_debian-11-arm"

  mgbuild_v4_ubuntu-22.04-arm:
    image: "memgraph/mgbuild:v4_ubuntu-22.04-arm"
    build:
      context: ubuntu-22.04-arm
      args:
        TOOLCHAIN_VERSION: "v4"
    extra_hosts:
      - "mgdeps-cache:10.42.16.10"
      - "bench-graph-api:10.42.16.10"
    container_name: "mgbuild_v4_ubuntu-22.04-arm"
