#include "httpconnection.hpp"
#include "method.hpp"
#include "httpparser.hpp"
#include "httpparsersettings.hpp"
#include "httpserver.hpp"
#include "version.hpp"
#include "ipv4.hpp"
#include "request.hpp"
#include "response.hpp"
#include "status_codes.hpp"

#include "httpconnection.inl"
#include "httpparser.inl"
#include "httpparsersettings.inl"
#include "httpserver.inl"
#include "ipv4.inl"
#include "response.inl"
