// Copyright 2026 Memgraph Ltd.
//
// Use of this software is governed by the Business Source License
// included in the file licenses/BSL.txt; by using this file, you agree to be bound by the terms of the Business Source
// License, and you may not use this file except in compliance with the Business Source License.
//
// As of the Change Date specified in that file, in accordance with
// the Business Source License, use of this software will be governed
// by the Apache License, Version 2.0, included in the file
// licenses/APL.txt.

#include "query/plan_v2/cost/builtin_estimator.hpp"

#include <algorithm>
#include <cmath>
#include <optional>

#include "query/plan_v2/egraph/egraph_internal.hpp"

namespace memgraph::query::plan::v2 {

using enum symbol;

namespace {

/// Best-effort: if `eclass_id` carries a `Literal` e-node whose stored value
/// is an int, return it.
///
/// TODO: replace with EClass Analysis read once analysis_data is live.
/// Today we walk the e-class for a Literal e-node and index into the
/// trait's id -> value vector.
auto TryReadIntLiteral(EGraph const &eg, egraph const &facade, planner::core::EClassId eclass_id)
    -> std::optional<int64_t> {
  auto const canonical = eg.find(eclass_id);
  auto const &cls = eg.eclass(canonical);
  auto const &lit_info = impl_of(facade).graph.storage<Literal>().info;

  for (auto enode_id : cls.nodes()) {
    auto const &enode = eg.get_enode(enode_id);
    if (enode.symbol() != Literal) continue;
    auto const id = enode.disambiguator();
    if (id >= lit_info.size()) continue;
    auto const &val = *lit_info[id];
    if (val.IsInt()) return val.ValueInt();
    // Tolerate doubles that exactly represent an integer (e.g. range(0.0,
    // 5.0) coming from a parser that promoted ints to doubles).  Reject
    // non-integral doubles - they're not what range expects anyway.
    if (val.IsDouble()) {
      auto const d = val.ValueDouble();
      if (std::isfinite(d) && std::trunc(d) == d) return static_cast<int64_t>(d);
    }
    return std::nullopt;
  }
  return std::nullopt;
}

/// range(start, end[, step]).  Only two-arg int-literal start/end with implicit
/// step=1 is modelled; non-literal or non-int args fall back to
/// kDefaultListSize.  Cypher range is inclusive on both ends.
// TODO: This estimate is the size of the list generated by range.  We should
//       be able to support both cardinality (number of pulls) and size
//       (length of the produced list):
//         WITH   range(1,100) AS x RETURN x;  -- cardinality 1
//         UNWIND range(1,100) AS x RETURN x;  -- cardinality 100
auto EstimateRange(EGraph const &eg, egraph const &facade, std::span<planner::core::EClassId const> arg_eclasses)
    -> double {
  if (arg_eclasses.size() < 2) return kDefaultListSize;
  auto const a = TryReadIntLiteral(eg, facade, arg_eclasses[0]);
  auto const b = TryReadIntLiteral(eg, facade, arg_eclasses[1]);
  if (!a || !b) return kDefaultListSize;
  return std::max(0.0, static_cast<double>(*b) - static_cast<double>(*a) + 1.0);
}

auto EstimateFunction(EGraph const &eg, egraph const &facade, planner::core::ENode<symbol> const &enode,
                      std::span<planner::core::EClassId const> arg_eclasses) -> double {
  auto const *info = facade.FunctionInfoById(enode.disambiguator());
  if (info == nullptr) return kDefaultListSize;

  switch (info->kind) {
    case BuiltinKind::Range:
      return EstimateRange(eg, facade, arg_eclasses);
    case BuiltinKind::Unknown:
      return kDefaultListSize;
  }
  return kDefaultListSize;
}

}  // namespace

BuiltinEstimator::BuiltinEstimator(egraph const &f) : CardinalityEstimator(impl_of(f).graph.core()), facade(f) {}

auto BuiltinEstimator::Estimate(planner::core::ENode<symbol> const &enode,
                                std::span<planner::core::EClassId const> children) const -> double {
  switch (enode.symbol()) {
    case Function:
      return EstimateFunction(eg_, facade, enode, children);
    default:
      return kDefaultCardinalityEstimate;
  }
}

}  // namespace memgraph::query::plan::v2
