CREATE (a1:Account {id: 1, name: 'Alice', flagged: false, balance: 50000});
CREATE (a2:Account {id: 2, name: 'Bob', flagged: true, balance: 12000});
CREATE (a3:Account {id: 3, name: 'Charlie', flagged: false, balance: 75000});
CREATE (a4:Account {id: 4, name: 'Diana', flagged: true, balance: 3000});
CREATE (a5:Account {id: 5, name: 'Eve', flagged: false, balance: 90000});
CREATE (a6:Account {id: 6, name: 'Frank', flagged: false, balance: 200});
CREATE (m1:Merchant {id: 101, name: 'ShopA', category: 'retail'});
CREATE (m2:Merchant {id: 102, name: 'ShopB', category: 'electronics'});
CREATE (d1:Device {id: 201, type: 'mobile', ip: '10.0.0.1'});
CREATE (d2:Device {id: 202, type: 'desktop', ip: '10.0.0.2'});
MATCH (a:Account {id: 1}), (b:Account {id: 2}) CREATE (a)-[:TRANSFERRED_TO {amount: 15000, timestamp: 1000}]->(b);
MATCH (a:Account {id: 2}), (b:Account {id: 3}) CREATE (a)-[:TRANSFERRED_TO {amount: 8000, timestamp: 1001}]->(b);
MATCH (a:Account {id: 3}), (b:Account {id: 4}) CREATE (a)-[:TRANSFERRED_TO {amount: 25000, timestamp: 1002}]->(b);
MATCH (a:Account {id: 4}), (b:Account {id: 5}) CREATE (a)-[:TRANSFERRED_TO {amount: 500, timestamp: 1003}]->(b);
MATCH (a:Account {id: 5}), (b:Account {id: 1}) CREATE (a)-[:TRANSFERRED_TO {amount: 12000, timestamp: 1004}]->(b);
MATCH (a:Account {id: 2}), (b:Account {id: 4}) CREATE (a)-[:TRANSFERRED_TO {amount: 30000, timestamp: 1005}]->(b);
MATCH (a:Account {id: 1}), (m:Merchant {id: 101}) CREATE (a)-[:PURCHASED_AT {amount: 200, timestamp: 1006}]->(m);
MATCH (a:Account {id: 2}), (m:Merchant {id: 102}) CREATE (a)-[:PURCHASED_AT {amount: 9999, timestamp: 1007}]->(m);
MATCH (a:Account {id: 1}), (d:Device {id: 201}) CREATE (a)-[:LOGGED_IN_FROM]->(d);
MATCH (a:Account {id: 2}), (d:Device {id: 201}) CREATE (a)-[:LOGGED_IN_FROM]->(d);
MATCH (a:Account {id: 3}), (d:Device {id: 202}) CREATE (a)-[:LOGGED_IN_FROM]->(d);
