
FROM ubuntu:22.04

ARG TOOLCHAIN_VERSION

ENV DEBIAN_FRONTEND=noninteractive

USER root


RUN apt update && apt install -y \
    ca-certificates wget git

RUN wget -q https://s3-eu-west-1.amazonaws.com/deps.memgraph.io/${TOOLCHAIN_VERSION}/${TOOLCHAIN_VERSION}-binaries-ubuntu-22.04-amd64.tar.gz \
    -O ${TOOLCHAIN_VERSION}-binaries-ubuntu-22.04-amd64.tar.gz \
    && tar xzvf ${TOOLCHAIN_VERSION}-binaries-ubuntu-22.04-amd64.tar.gz -C /opt

RUN git clone https://github.com/memgraph/memgraph.git


RUN /memgraph/environment/os/ubuntu-22.04.sh install TOOLCHAIN_RUN_DEPS
RUN /memgraph/environment/os/ubuntu-22.04.sh install MEMGRAPH_BUILD_DEPS

# FROM ubuntu:latest

# RUN apt-get update && apt-get install -y wget libcurl4

# COPY client /bin/

# ENTRYPOINT ["bin/client"]
