FROM ubuntu:24.04 AS mg_bench_client_build_base

SHELL ["/bin/bash", "-c"]
ARG TOOLCHAIN_VERSION
ARG TARGETARCH
ARG GIT_REF

ENV DEBIAN_FRONTEND=noninteractive

USER root

RUN apt update && apt install -y \
    ca-certificates wget git

RUN wget -q https://s3-eu-west-1.amazonaws.com/deps.memgraph.io/${TOOLCHAIN_VERSION}/${TOOLCHAIN_VERSION}-binaries-ubuntu-24.04-${TARGETARCH}.tar.gz \
    -O ${TOOLCHAIN_VERSION}-binaries-ubuntu-24.04-${TARGETARCH}.tar.gz \
    && tar xzvf ${TOOLCHAIN_VERSION}-binaries-ubuntu-24.04-${TARGETARCH}.tar.gz -C /opt

RUN git clone https://github.com/memgraph/memgraph.git && \
    if [ -n "$GIT_REF" ]; then \
        cd memgraph && \
        git checkout "$GIT_REF" \
        cd .. \
    fi

WORKDIR memgraph

RUN if [ ${TARGETARCH} = "amd64" ] ; then ./environment/os/ubuntu-24.04.sh install TOOLCHAIN_RUN_DEPS ; else ./environment/os/ubuntu-24.04-arm.sh install TOOLCHAIN_RUN_DEPS ; fi
RUN if [ ${TARGETARCH} = "amd64" ] ; then ./environment/os/ubuntu-24.04.sh install MEMGRAPH_BUILD_DEPS ; else ./environment/os/ubuntu-24.04-arm.sh install MEMGRAPH_BUILD_DEPS ; fi

RUN curl -fsSL https://deb.nodesource.com/setup_20.x | bash - && \
    apt-get update && \
    apt-get install -y nodejs

RUN useradd --create-home --shell /bin/bash memgraph \
    && chown -R memgraph:memgraph /memgraph

USER memgraph
ENV HOME=/home/memgraph

RUN source /opt/${TOOLCHAIN_VERSION}/activate && \
    ./init  && \
    rm -r build && \
    mkdir build && \
    cd build && \
    cmake -DCMAKE_BUILD_TYPE=release .. && \
    make -j$(nproc) memgraph__mgbench__client && \
    make .


FROM ubuntu:24.04

RUN apt-get update && apt-get install -y wget libcurl4 python3 && \
    rm -rf /var/lib/apt/lists/*

# Copy mgbench client to clean image
COPY --from=mg_bench_client_build_base /memgraph/build/tests/mgbench /bin
COPY --from=mg_bench_client_build_base /memgraph/tests/mgbench /mgbench

ENTRYPOINT ["python3", "/mgbench/benchmark.py"]
