CREATE (a1:Node {id: 1, name: 'A1'});
CREATE (a2:Node {id: 2, name: 'A2'});
CREATE (a3:Node {id: 3, name: 'A3'});
CREATE (a4:Node {id: 4, name: 'A4'});
CREATE (b1:Node {id: 5, name: 'B1'});
CREATE (b2:Node {id: 6, name: 'B2'});
CREATE (b3:Node {id: 7, name: 'B3'});
CREATE (b4:Node {id: 8, name: 'B4'});
CREATE (hub:Node {id: 9, name: 'HUB'});
MATCH (a:Node {id: 1}), (b:Node {id: 2}) CREATE (a)-[:LINK]->(b);
MATCH (a:Node {id: 2}), (b:Node {id: 3}) CREATE (a)-[:LINK]->(b);
MATCH (a:Node {id: 3}), (b:Node {id: 4}) CREATE (a)-[:LINK]->(b);
MATCH (a:Node {id: 4}), (b:Node {id: 9}) CREATE (a)-[:LINK]->(b);
MATCH (a:Node {id: 5}), (b:Node {id: 6}) CREATE (a)-[:LINK]->(b);
MATCH (a:Node {id: 6}), (b:Node {id: 7}) CREATE (a)-[:LINK]->(b);
MATCH (a:Node {id: 7}), (b:Node {id: 8}) CREATE (a)-[:LINK]->(b);
MATCH (a:Node {id: 8}), (b:Node {id: 9}) CREATE (a)-[:LINK]->(b);
MATCH (a:Node {id: 2}), (b:Node {id: 1}) CREATE (a)-[:LINK]->(b);
MATCH (a:Node {id: 3}), (b:Node {id: 2}) CREATE (a)-[:LINK]->(b);
MATCH (a:Node {id: 4}), (b:Node {id: 3}) CREATE (a)-[:LINK]->(b);
MATCH (a:Node {id: 9}), (b:Node {id: 4}) CREATE (a)-[:LINK]->(b);
MATCH (a:Node {id: 6}), (b:Node {id: 5}) CREATE (a)-[:LINK]->(b);
MATCH (a:Node {id: 7}), (b:Node {id: 6}) CREATE (a)-[:LINK]->(b);
MATCH (a:Node {id: 8}), (b:Node {id: 7}) CREATE (a)-[:LINK]->(b);
MATCH (a:Node {id: 9}), (b:Node {id: 8}) CREATE (a)-[:LINK]->(b);
