CREATE INDEX ON :__mg_vertex__(__mg_id__);
CREATE (:__mg_vertex__ {__mg_id__: 0, `value`: 6, `country`: "Austria"});
CREATE (:__mg_vertex__ {__mg_id__: 1, `value`: 7, `country`: "Hungary"});
CREATE (:__mg_vertex__ {__mg_id__: 2, `value`: 8, `country`: "Romania"});
CREATE (:__mg_vertex__ {__mg_id__: 3, `value`: 9, `country`: "Bulgaria"});
CREATE (:__mg_vertex__ {__mg_id__: 4, `value`: 10, `country`: "Spain"});
CREATE (:__mg_vertex__ {__mg_id__: 5, `value`: 11, `country`: "Latvia"});
CREATE (:__mg_vertex__ {__mg_id__: 6, `value`: 12, `country`: "Russia"});
CREATE (:__mg_vertex__ {__mg_id__: 7, `value`: 13, `country`: "Poland"});
CREATE (:__mg_vertex__ {__mg_id__: 8, `value`: 14, `country`: "Czech Republic"});
CREATE (:__mg_vertex__ {__mg_id__: 9, `value`: 15, `country`: "Moldova"});
MATCH (u:__mg_vertex__), (v:__mg_vertex__) WHERE u.__mg_id__ = 0 AND v.__mg_id__ = 1 CREATE (u)-[:`NEIGHBOUR`]->(v);
MATCH (u:__mg_vertex__), (v:__mg_vertex__) WHERE u.__mg_id__ = 2 AND v.__mg_id__ = 1 CREATE (u)-[:`NEIGHBOUR`]->(v);
MATCH (u:__mg_vertex__), (v:__mg_vertex__) WHERE u.__mg_id__ = 4 AND v.__mg_id__ = 6 CREATE (u)-[:`NOT_NEIGHBOUR`]->(v);
MATCH (u:__mg_vertex__), (v:__mg_vertex__) WHERE u.__mg_id__ = 5 AND v.__mg_id__ = 0 CREATE (u)-[:`NOT_NEIGHBOUR`]->(v);
DROP INDEX ON :__mg_vertex__(__mg_id__);
MATCH (u) REMOVE u:__mg_vertex__, u.__mg_id__;