name: "Community build and test"
concurrency:
  group: ${{ github.head_ref || github.sha }}
  cancel-in-progress: true

on:
  workflow_call:
    inputs:
      arch:
        type: string
        description: "Target architecture (amd, arm). Default value is amd."
        default: 'amd'
      build_type:
        type: string
        description: "Memgraph Build type (Debug, Release, RelWithDebInfo). Default value is Release."
        default: 'Release'
      os:
        type: string
        description: "Target os. Default value is debian-12."
        default: 'debian-12'
      toolchain:
        type: string
        description: "Toolchain version (v4, v5). Default value is v5."
        default: 'v5'

jobs:
  build_and_test:
    name: "Build and test"
    runs-on: [self-hosted, Linux, X64, DockerMgBuild]
    timeout-minutes: 60
    env:
      MEMGRAPH_ENTERPRISE_LICENSE: ${{ secrets.MEMGRAPH_ENTERPRISE_LICENSE }}
      MEMGRAPH_ORGANIZATION_NAME: ${{ secrets.MEMGRAPH_ORGANIZATION_NAME }}
      OS: ${{ inputs.os }}
      TOOLCHAIN: ${{ inputs.toolchain }}
      ARCH: ${{ inputs.arch }}
      BUILD_TYPE: ${{ inputs.build_type }}
    
    steps:
      - name: Set up repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Spin up mgbuild container
        run: |
          ./release/package/mgbuild.sh \
          --toolchain $TOOLCHAIN \
          --os $OS \
          --arch $ARCH \
          run

      - name: Build community binary
        run: |
          ./release/package/mgbuild.sh \
          --toolchain $TOOLCHAIN \
          --os $OS \
          --arch $ARCH \
          --build-type $BUILD_TYPE \
          --threads $THREADS \
          build-memgraph --community

      - name: Run unit tests
        run: |
          ./release/package/mgbuild.sh \
          --toolchain $TOOLCHAIN \
          --os $OS \
          --arch $ARCH \
          --threads $THREADS \
          --enterprise-license $MEMGRAPH_ENTERPRISE_LICENSE \
          --organization-name $MEMGRAPH_ORGANIZATION_NAME \
          test-memgraph unit

      - name: Stop mgbuild container
        if: always()
        run: |
          ./release/package/mgbuild.sh \
          --toolchain $TOOLCHAIN \
          --os $OS \
          --arch $ARCH \
          stop --remove
