#!/bin/bash -e

tools=(
  go
  dotnet
  npm
  node
  java
  javac
  mono
  mcs
  virtualenv
)

for tool in ${tools[@]}; do
  if ! which $tool >/dev/null; then
    echo "$tool not installed!"
  fi
done;
