#!/bin/bash -e

tools=(
    go
    dotnet
    npm
    node
    java
    javac
    mono
    mcs
    virtualenv
)

is_ok=true
for tool in "${tools[@]}"; do
    if ! which "$tool" >/dev/null; then
        is_ok=false
        echo "$tool not installed!"
    fi
done
if [ "$is_ok" = true ]; then
    exit 0
else
    exit 1
fi
