name: Run benchmark on pokec large dataset

on:
  workflow_dispatch:
    inputs:
      build_type:
        type: choice
        description: "Memgraph Build type."
        default: 'Release'
        options:
          - Release
          - RelWithDebInfo

jobs:
  benchmark_on_pokec_large:
    name: "Benchmark on pokec large dataset"
    runs-on: [self-hosted, Linux, X64, DockerMgBuild]
    env:
        THREADS: 24
        MEMGRAPH_ENTERPRISE_LICENSE: ${{ secrets.MEMGRAPH_ENTERPRISE_LICENSE }}
        MEMGRAPH_ORGANIZATION_NAME: ${{ secrets.MEMGRAPH_ORGANIZATION_NAME }}

    steps:
        - name: Set up repository
          uses: actions/checkout@v4
          with:
            # Number of commits to fetch. `0` indicates all history for all
            # branches and tags. (default: 1)
            fetch-depth: 0
        - name: Log in to Docker Hub
          uses: docker/login-action@v3
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}

        - name: Spin up mgbuild container
          run: |
            ./release/package/mgbuild.sh \
            --toolchain $TOOLCHAIN \
            --os $OS \
            --arch $ARCH \
            run

        - name: Build debug binary
          run: |
            ./release/package/mgbuild.sh \
            --toolchain $TOOLCHAIN \
            --os $OS \
            --arch $ARCH \
            --build-type  ${{ github.event.inputs.build_type }} \
            --threads $THREADS \
            build-memgraph

        - name: Get branch name (merge)
          if: github.event_name != 'pull_request'
          shell: bash
          run: echo "BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/} | tr / -)" >> $GITHUB_ENV

        - name: Get branch name (pull request)
          if: github.event_name == 'pull_request'
          shell: bash
          run: echo "BRANCH_NAME=$(echo ${GITHUB_HEAD_REF} | tr / -)" >> $GITHUB_ENV

        - name: Run mgbench
          run: |
            ./release/package/mgbuild.sh \
            --toolchain $TOOLCHAIN \
            --os $OS \
            --arch $ARCH \
            --enterprise-license $MEMGRAPH_ENTERPRISE_LICENSE \
            --organization-name $MEMGRAPH_ORGANIZATION_NAME \
            test-memgraph mgbench

        - name: Upload mgbench results
          run: |
            ./release/package/mgbuild.sh \
            --toolchain $TOOLCHAIN \
            --os $OS \
            --arch $ARCH \
            --enterprise-license $MEMGRAPH_ENTERPRISE_LICENSE \
            --organization-name $MEMGRAPH_ORGANIZATION_NAME \
            test-memgraph upload-to-bench-graph \
            --benchmark-name "mgbench" \
            --benchmark-results "../../tests/mgbench/benchmark_result.json" \
            --github-run-id "${{ github.run_id }}" \
            --github-run-number "${{ github.run_number }}" \
            --head-branch-name "${{ env.BRANCH_NAME }}"

        - name: Stop mgbuild container
          if: always()
          run: |
            ./release/package/mgbuild.sh \
            --toolchain $TOOLCHAIN \
            --os $OS \
            --arch $ARCH \
            stop --remove
