name: "Check Diff for flakiness"
concurrency:
  group: ${{ github.head_ref }}-${{ github.sha }}
  cancel-in-progress: true

on:
  schedule:
    - cron: "0 1 * * *" #UTC
  workflow_dispatch:
    inputs:
      community_core:
        type: boolean
        default: true
        description: "Community: Core"
      coverage_core:
        type: boolean
        default: true
        description: "Coverage: Core"
      debug_core:
        type: boolean
        default: true
        description: "Debug: Core"
      debug_integration:
        type: boolean
        default: true
        description: "Debug: Integration"
      jepsen_core:
        type: boolean
        default: true
        description: "Jepsen: Core"
      release_core:
        type: boolean
        default: true
        description: "Release: Core"
      release_benchmark:
        type: boolean
        default: false
        description: "Release: Benchmark"
      release_e2e:
        type: boolean
        default: true
        description: "Release: E2E"
      release_stress:
        type: boolean
        default: true
        description: "Release: Stress"
      mage_amd:
        type: boolean
        default: true
        description: "MAGE: AMD"
      mage_arm:
        type: boolean
        default: false
        description: "MAGE: ARM"
      mage_cuda:
        type: boolean
        default: false
        description: "MAGE: CUDA"
      mgcxx_unit:
        type: boolean
        default: true
        description: "MGCXX: Unit"
      flakiness_runs:
        type: number
        default: 3
        required: true
        description: "Check for flakiness by running every selected job multiple times. Enter a number between 2 and 20."

jobs:
  DiffSetup:
    runs-on: ubuntu-latest
    outputs:
      run_community_core: ${{ steps.setup.outputs.run_community_core }}
      run_coverage_core: ${{ steps.setup.outputs.run_coverage_core }}
      run_debug_core: ${{ steps.setup.outputs.run_debug_core }}
      run_debug_integration: ${{ steps.setup.outputs.run_debug_integration }}
      run_jepsen_core: ${{ steps.setup.outputs.run_jepsen_core }}
      run_release_core: ${{ steps.setup.outputs.run_release_core }}
      run_release_benchmark: ${{ steps.setup.outputs.run_release_benchmark}}
      run_release_e2e: ${{ steps.setup.outputs.run_release_e2e }}
      run_release_stress: ${{ steps.setup.outputs.run_release_stress }}
      run_mage_amd: ${{ steps.setup.outputs.run_mage_amd }}
      run_mage_arm: ${{ steps.setup.outputs.run_mage_arm }}
      run_mage_cuda: ${{ steps.setup.outputs.run_mage_cuda }}
      run_mgcxx_unit: ${{ steps.setup.outputs.run_mgcxx_unit }}
      runs: ${{ steps.setup_flakiness.outputs.runs }}
    env:
      GH_CONTEXT: ${{ toJson(github) }}
      GH_CONTEXT_FILE_NAME: github_context.json
      FLAKINESS_RUNS: ${{ github.event.inputs.flakiness_runs || 10 }}
    steps:
      - name: Set up repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2
        with:
          fetch-depth: 0
      - name: Dump GitHub context
        run: echo "$GH_CONTEXT" >> "$GH_CONTEXT_FILE_NAME"
      - name: Set up diff execution
        id: setup
        run: ./tools/ci/diff_setup.py --gh-context-path "$GH_CONTEXT_FILE_NAME" --base-branch "origin/master"
      - name: Set up flakiness runs
        id: setup_flakiness
        run: |
          if [[ $FLAKINESS_RUNS -lt 2 ]] || [[ $FLAKINESS_RUNS -gt 20 ]]; then
            echo "ERROR: Selected 'flakiness_runs' value is invalid. Please select a value between 2 and 20."
            exit 1
          fi
          sequence=""
          for i in $(seq 1 $FLAKINESS_RUNS); do
            sequence+="${i},"
          done
          echo "runs=[${sequence::-1}]" >> $GITHUB_OUTPUT

  Community:
    needs: DiffSetup
    strategy:
      fail-fast: false
      max-parallel: 3
      matrix:
        run_no: ${{ fromJSON(needs.DiffSetup.outputs.runs) }}
    uses: ./.github/workflows/diff_community.yaml
    with:
      arch: 'amd'
      os: 'ubuntu-24.04'
      run_core: ${{ needs.DiffSetup.outputs.run_community_core }}
      run_id: "${{ matrix.run_no }}"
      ref: ${{ github.sha }}
    secrets: inherit

  Coverage:
    needs: DiffSetup
    strategy:
      fail-fast: false
      max-parallel: 3
      matrix:
        run_no: ${{ fromJSON(needs.DiffSetup.outputs.runs) }}
    uses: ./.github/workflows/diff_coverage.yaml
    with:
      arch: 'amd'
      os: 'ubuntu-24.04'
      run_core: ${{ needs.DiffSetup.outputs.run_coverage_core }}
      run_clang_tidy: ${{ needs.DiffSetup.outputs.run_coverage_core }}
      run_id: "${{ matrix.run_no }}"
      ref: ${{ github.sha }}
    secrets: inherit

  Debug:
    needs: DiffSetup
    strategy:
      fail-fast: false
      max-parallel: 3
      matrix:
        run_no: ${{ fromJSON(needs.DiffSetup.outputs.runs) }}
    uses: ./.github/workflows/diff_debug.yaml
    with:
      arch: 'amd'
      os: 'ubuntu-24.04'
      run_core: ${{ needs.DiffSetup.outputs.run_debug_core }}
      run_integration: ${{ needs.DiffSetup.outputs.run_debug_integration }}
      run_id: "${{ matrix.run_no }}"
      ref: ${{ github.sha }}
    secrets: inherit

  Jepsen:
    needs: DiffSetup
    strategy:
      fail-fast: false
      max-parallel: 3
      matrix:
        run_no: ${{ fromJSON(needs.DiffSetup.outputs.runs) }}
    uses: ./.github/workflows/diff_jepsen.yaml
    with:
      run_core: ${{ needs.DiffSetup.outputs.run_jepsen_core }}
      run_id: "${{ matrix.run_no }}"
      ref: ${{ github.sha }}
    secrets: inherit

  Release:
    needs: DiffSetup
    strategy:
      fail-fast: false
      max-parallel: 3
      matrix:
        run_no: ${{ fromJSON(needs.DiffSetup.outputs.runs) }}
    uses: ./.github/workflows/diff_release.yaml
    with:
      arch: 'amd'
      os: 'ubuntu-24.04'
      run_core: ${{ needs.DiffSetup.outputs.run_release_core }}
      run_benchmark: ${{ needs.DiffSetup.outputs.run_release_benchmark =='true' && github.event_name == 'workflow_dispatch' }}
      run_e2e: ${{ needs.DiffSetup.outputs.run_release_e2e }}
      run_stress: ${{ needs.DiffSetup.outputs.run_release_stress }}
      run_id: "${{ matrix.run_no }}"
      ref: ${{ github.sha }}
    secrets: inherit

  Mage:
    needs: DiffSetup
    strategy:
      fail-fast: false
      max-parallel: 3
      matrix:
        run_no: ${{ fromJSON(needs.DiffSetup.outputs.runs) }}
    uses: ./.github/workflows/diff_mage.yml
    with:
      run_amd: ${{ needs.DiffSetup.outputs.run_mage_amd == 'true' }}
      run_arm: ${{ needs.DiffSetup.outputs.run_mage_arm == 'true' }}
      run_cuda: ${{ needs.DiffSetup.outputs.run_mage_cuda == 'true' }}
      run_id: "${{ matrix.run_no }}"
      ref: ${{ github.sha }}
    secrets: inherit

  MGCXX:
    needs: DiffSetup
    strategy:
      fail-fast: false
      max-parallel: 3
      matrix:
        run_no: ${{ fromJSON(needs.DiffSetup.outputs.runs) }}
    uses: ./.github/workflows/diff_mgcxx.yml
    with:
      run_test: ${{ needs.DiffSetup.outputs.run_mgcxx_unit == 'true' }}
      run_id: "${{ matrix.run_no }}"
      ref: ${{ github.sha }}
    secrets: inherit
