name: Daily Stress Tests

on:
  workflow_dispatch:
  schedule:
    - cron: "0 22 * * *"

jobs:
  release_benchmarks:
    name: "Release benchmarks"
    runs-on: [self-hosted, Linux, X64, Diff, Gen7]
    timeout-minutes: 120
    env:
      ARCH: "amd"
      OS: "ubuntu-24.04"
      TOOLCHAIN: "v6"
      BUILD_TYPE: "Release"
      MEMGRAPH_ENTERPRISE_LICENSE: ${{ secrets.MEMGRAPH_ENTERPRISE_LICENSE }}
      MEMGRAPH_ORGANIZATION_NAME: ${{ secrets.MEMGRAPH_ORGANIZATION_NAME }}

    steps:
      - name: Set up repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Log in to Docker Hub
        uses: ./.github/actions/docker-login
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Spin up mgbuild container
        run: |
          ./release/package/mgbuild.sh \
          --toolchain $TOOLCHAIN \
          --os $OS \
          --arch $ARCH \
          run

      - name: Build release binary
        run: |
          ./release/package/mgbuild.sh \
          --toolchain $TOOLCHAIN \
          --os $OS \
          --arch $ARCH \
          --build-type $BUILD_TYPE \
          build-memgraph

      - name: Initialize tests
        run: |
          ./release/package/mgbuild.sh \
          --toolchain $TOOLCHAIN \
          --os $OS \
          --arch $ARCH \
          init-tests

      - name: Get branch name
        shell: bash
        run: |
          if [[ ${{ github.event_name }} == 'pull_request' ]]; then
            echo "BRANCH_NAME=$(echo ${GITHUB_HEAD_REF} | tr / -)" >> $GITHUB_ENV
          else
            echo "BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/} | tr / -)" >> $GITHUB_ENV
          fi

      - name: Run custom stress tests
        run: |
          ./release/package/mgbuild.sh \
          --toolchain $TOOLCHAIN \
          --os $OS \
          --arch $ARCH \
          --enterprise-license $MEMGRAPH_ENTERPRISE_LICENSE \
          --organization-name $MEMGRAPH_ORGANIZATION_NAME \
          test-memgraph stress-daily

      - name: Upload custom stress test results
        run: |
          ./release/package/mgbuild.sh \
          --toolchain $TOOLCHAIN \
          --os $OS \
          --arch $ARCH \
          --enterprise-license $MEMGRAPH_ENTERPRISE_LICENSE \
          --organization-name $MEMGRAPH_ORGANIZATION_NAME \
          test-memgraph upload-to-bench-graph \
          --benchmark-name "stress-daily" \
          --benchmark-results "../../tests/stress/metrics_metrics-monitoring-basic.json" \
          --github-run-id "${{ github.run_id }}" \
          --github-run-number "${{ github.run_number }}" \
          --head-branch-name "${{ env.BRANCH_NAME }}"

      - name: Stop mgbuild container
        if: always()
        run: |
          ./release/package/mgbuild.sh \
          --toolchain $TOOLCHAIN \
          --os $OS \
          --arch $ARCH \
          stop --remove

      - name: Clean up Docker
        run: |
          ./tools/docker_cleanup.sh
