name: Clang-tidy experiment on full code base

on:
  push:
    branches:
      - 'T0520-MG-clang-tidy-usability'

jobs:
  community_build:
    name: "Experimental clang-tidy check"
    runs-on: [self-hosted, Linux, X64, Ubuntu20.04]
    env:
      THREADS: 24

    steps:
      - name: Set up repository
        uses: actions/checkout@a81bbbf8298c0fa03ea29cdc473d45769f953675
        with:
          # Number of commits to fetch. `0` indicates all history for all
          # branches and tags. (default: 1)
          fetch-depth: 0

      - name: Build debug binaries
        run: |
          # Activate toolchain.
          source /opt/toolchain-v2/activate

          # Initialize dependencies.
          ./init

          # Build debug binaries.

          cd build
          cmake .. -DCMAKE_EXPORT_COMPILE_COMMANDS=ON
          make -j$THREADS

      - name: Run clang-tidy
        run: |
          source /opt/toolchain-v2/activate

          # The results are also written to standard output in order to retaion them in the logs
          ./tools/github/clang-tidy/run-clang-tidy.py -p build -j $THREADS -clang-tidy-binary=/opt/toolchain-v2/bin/clang-tidy "$PWD/src/*" |
            tee ./build/full_clang_tidy_output.txt

      - name: Summarize clang-tidy results
        run: cat ./build/full_clang_tidy_output.txt | ./tools/github/clang-tidy/count_errors.sh
