name: Release Legacy

# TODO(gitbuda): Upload all packages to Github.
# TODO(gitbuda): Do on: workflow_dispatch

on:
  push:
    branches:
      - 'T0499-MG-auto-build-all-packages'

jobs:
  centos7_community_build:
    runs-on: [self-hosted, Linux, X64, storm]
    timeout-minutes: 60
    steps:
      - name: "Set up repository"
        uses: actions/checkout@v2
      - name: "Build package"
        run: |
          ./release/legacy/run.sh package community centos-7

  debian9_community_build:
    runs-on: [self-hosted, Linux, X64, storm]
    timeout-minutes: 60
    steps:
      - name: "Set up repository"
        uses: actions/checkout@v2
      - name: "Build package"
        run: |
          ./release/legacy/run.sh package community debian-9

  debian10_and_docker_community_build:
    runs-on: [self-hosted, Linux, X64, storm]
    timeout-minutes: 60
    steps:
      - name: "Set up repository"
        uses: actions/checkout@v2
      - name: "Build package"
        run: |
          cd release/legacy
          ./run.sh package community debian-10
          ./run.sh docker

  ubuntu18_community_build:
    runs-on: [self-hosted, Linux, X64, storm]
    timeout-minutes: 60
    steps:
      - name: "Set up repository"
        uses: actions/checkout@v2
      - name: "Build package"
        run: |
          ./release/legacy/run.sh package community ubuntu-18.04

  centos7_enterprise_build:
    runs-on: [self-hosted, Linux, X64, storm]
    timeout-minutes: 60
    steps:
      - name: "Set up repository"
        uses: actions/checkout@v2
      - name: "Build package"
        run: |
          ./release/legacy/run.sh package enterprise centos-7

  debian9_enterprise_build:
    runs-on: [self-hosted, Linux, X64, storm]
    timeout-minutes: 60
    steps:
      - name: "Set up repository"
        uses: actions/checkout@v2
      - name: "Build package"
        run: |
          ./release/legacy/run.sh package enterprise debian-9

  debian10_and_docker_enterprise_build:
    runs-on: [self-hosted, Linux, X64, storm]
    timeout-minutes: 60
    steps:
      - name: "Set up repository"
        uses: actions/checkout@v2
      - name: "Build package"
        run: |
          cd release/legacy
          ./run.sh package enterprise debian-10
          ./run.sh docker

  ubuntu18_enterprise_build:
    runs-on: [self-hosted, Linux, X64, storm]
    timeout-minutes: 60
    steps:
      - name: "Set up repository"
        uses: actions/checkout@v2
      - name: "Build package"
        run: |
          ./release/legacy/run.sh package enterprise ubuntu-18.04
