name: In development - Release Debian 10

on:
  pull_request:
    paths-ignore:
      - "docs/**"
      - "**/*.md"
      - ".clang-format"
      - "CODEOWNERS"
      - "licenses/*"

jobs:
  debug_build:
    name: "Debug build"
    runs-on: [self-hosted, Linux, X64, Debian10]
    env:
      THREADS: 24
      MEMGRAPH_ENTERPRISE_LICENSE: ${{ secrets.MEMGRAPH_ENTERPRISE_LICENSE }}
      MEMGRAPH_ORGANIZATION_NAME: ${{ secrets.MEMGRAPH_ORGANIZATION_NAME }}

    steps:
      - name: Set up repository
        uses: actions/checkout@v3
        with:
          # Number of commits to fetch. `0` indicates all history for all
          # branches and tags. (default: 1)
          fetch-depth: 0

      - name: Build debug binaries
        run: |
          # Activate toolchain.
          source /opt/toolchain-v4/activate

          # Initialize dependencies.
          ./init

          # Build debug binaries.
          cd build
          cmake ..
          make -j$THREADS
      
      - name: Upload build dir to artifacts
        uses: actions/upload-artifact@v3
        with:
          name: debug-build
          path: build/

  debug_drivers_tests:
    name: "Debug drivers tests"
    needs: debug_build
    runs-on: [self-hosted, Linux, X64, Debian10]
    steps:
      - name: Set up repository
        uses: actions/checkout@v3
        with:
          # Number of commits to fetch. `0` indicates all history for all
          # branches and tags. (default: 1)
          fetch-depth: 0

      - name: Download memgraph package
        uses: actions/download-artifact@v3
        with:
          name: debug-build

      - name: Run drivers tests
        run: |
          ./tests/drivers/run.sh

  debug_integration_tests:
    name: "Debug integration tests"
    needs: debug_build
    runs-on: [self-hosted, Linux, X64, Debian10]
    steps:
      - name: Set up repository
        uses: actions/checkout@v3
        with:
          # Number of commits to fetch. `0` indicates all history for all
          # branches and tags. (default: 1)
          fetch-depth: 0

      - name: Download memgraph package
        uses: actions/download-artifact@v3
        with:
          name: debug-build

      - name: Run integration tests
        run: |
          ./tests/integration/run.sh

  debug_Ctest_tests:
    name: "Debug CTest tests"
    needs: debug_build
    runs-on: [self-hosted, Linux, X64, Debian10]
    steps:
      - name: Set up repository
        uses: actions/checkout@v3
        with:
          # Number of commits to fetch. `0` indicates all history for all
          # branches and tags. (default: 1)
          fetch-depth: 0

      - name: Download memgraph package
        uses: actions/download-artifact@v3
        with:
          name: debug-build

      - name: Run leftover CTest tests
        run: |
          # Activate toolchain.
          source /opt/toolchain-v4/activate

          # Run leftover CTest tests (all except unit and benchmark tests).
          cd build
          ctest -E "(memgraph__unit|memgraph__benchmark)" --output-on-failure

  debug_cppcheck_tests:
    name: "Debug cppchek and clang-format"
    needs: debug_build
    runs-on: [self-hosted, Linux, X64, Debian10]
    steps:
      - name: Set up repository
        uses: actions/checkout@v3
        with:
          # Number of commits to fetch. `0` indicates all history for all
          # branches and tags. (default: 1)
          fetch-depth: 0

      - name: Download memgraph package
        uses: actions/download-artifact@v3
        with:
          name: debug-build

      - name: Run cppcheck and clang-format
        run: |
          # Activate toolchain.
          source /opt/toolchain-v4/activate

          # Run cppcheck and clang-format.
          cd tools/github
          ./cppcheck_and_clang_format diff

      - name: Save cppcheck and clang-format errors
        uses: actions/upload-artifact@v3
        with:
          name: "Code coverage"
          path: tools/github/cppcheck_and_clang_format.txt
