name: Stress test large Debian 10

on:
  workflow_dispatch:
    inputs:
      build_type:
        type: choice
        description: "Memgraph Build type. Default value is Release."
        default: 'Release'
        options:
          - Release
          - RelWithDebInfo

  schedule:
    - cron: "0 22 * * *"

jobs:
  stress_test_large:
    name: "Stress test large"
    runs-on: [self-hosted, Linux, X64, Debian10, BigMemory]
    env:
      THREADS: 24
      MEMGRAPH_ENTERPRISE_LICENSE: ${{ secrets.MEMGRAPH_ENTERPRISE_LICENSE }}
      MEMGRAPH_ORGANIZATION_NAME: ${{ secrets.MEMGRAPH_ORGANIZATION_NAME }}
    timeout-minutes: 960

    steps:
      - name: Set up repository
        uses: actions/checkout@v3
        with:
          # Number of commits to fetch. `0` indicates all history for all
          # branches and tags. (default: 1)
          fetch-depth: 0

      - name: Build release binaries
        run: |
          # Activate toolchain.
          source /opt/toolchain-v4/activate

          # Initialize dependencies.
          ./init

          # Set default build_type to Release
          INPUT_BUILD_TYPE=${{ github.event.inputs.build_type }}
          BUILD_TYPE=${INPUT_BUILD_TYPE:-"Release"}

          # Build release binaries.
          cd build
          cmake -DCMAKE_BUILD_TYPE=$BUILD_TYPE ..
          make -j$THREADS

      - name: Run stress test (large)
        run: |
          cd tests/stress
          ./continuous_integration --large-dataset
