name: Stress test large
concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

on:
  workflow_dispatch:
    inputs:
      build_type:
        type: choice
        description: "Memgraph Build type. Default value is Release."
        default: 'Release'
        options:
          - Release
          - RelWithDebInfo
      os:
        type: choice
        description: "Target OS on which the release tests will be run. Select 'all' if you want to package for every listed OS."
        default: 'ubuntu-24.04'
        options:
          - all
          - centos-9
          - centos-10
          - debian-12
          - debian-13
          - fedora-42
          - rocky-10
          - ubuntu-22.04
          - ubuntu-24.04
  push:
    tags:
      - "v*.*.*-rc*"
      - "v*.*-rc*"

jobs:
  StressTestLargeIndividual:
    if: ${{ !github.event.inputs.os || github.event.inputs.os != 'all'  && !contains(github.event.head_commit.message, '[skip tests]') }}
    uses: ./.github/workflows/reusable_release_tests.yaml
    with:
      os: ${{ github.event.inputs.os || 'ubuntu-24.04' }}
      arch: "amd"
      threads: 24
      build_type: ${{ github.event.inputs.build_type || 'Release' }}
      run_stress_large: 'true'
      run_release_tests: 'false'
    secrets: inherit

  StressTestLargeAll:
    if: ${{ github.event.inputs.os == 'all' }}
    strategy:
      matrix:
        os: [centos-9, centos-10, debian-12, debian-13, fedora-42, rocky-10, ubuntu-22.04, ubuntu-24.04]
    uses: ./.github/workflows/reusable_release_tests.yaml
    with:
      os: ${{ matrix.os }}
      arch: "amd"
      threads: 24
      build_type: ${{ github.event.inputs.build_type || 'Release' }}
      run_stress_large: 'true'
      run_release_tests: 'false'
    secrets: inherit
