name: Test Jepsen Refresh Cluster 
concurrency:
  group: ${{ github.head_ref || github.sha }}
  cancel-in-progress: true

on:
  workflow_dispatch:
  pull_request:
    paths-ignore:
      - "docs/**"
      - "**/*.md"
      - ".clang-format"
      - "CODEOWNERS"
      - "licenses/*"

release_jepsen_test:
    name: "Release Jepsen Test"
    strategy:
      fail-fast: false
      matrix:
        hostname: [mantis, captain-america, mystique, professor-x, nightcrawler, hulk, scarlet-witch, iron-man, storm, thanos, hela, jean-grey, venom, black-panther, deadpool, gamora, black-widow, magneto, ant-man]
    runs-on: [self-hosted, "${{ matrix.hostname }}"]
    timeout-minutes: 10

    steps:
      - name: Set up repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Refresh Jepsen Cluster
        run: |
          cd tests/jepsen
          ./run.sh cluster-refresh
